### ISSUE TITLE
Benchmarking the MultiheadDilatedAttention Class

### ISSUE THREAD

**Issue by MHarris021** [fkodom/dilated-attention-pytorch#3]
@fkodom 
Thank you for all of your help with my last issue. I'm trying to benchmark the MultiheadDilatedAttention class from the dilated_attention_pytorch directory similarly to how the DilatedAttention class was benchmarked. However, I don't really understand what the einops.rearrange command is doing (Numerical Linear Algebra was a long time ago) specifically the following calls:

```
       q = rearrange(q, "b n (h d) -> b n h d", h=self.num_heads)
        k = rearrange(k, "b n (h d) -> b n h d", h=self.num_heads)
        v = rearrange(v, "b n (h d) -> b n h d", h=self.num_heads)      
```

I understand that they are unfolding the 'd' dimension into separate attention heads from your comments, but not quite sure what they are expecting in terms of a tensor shape and they are currently erroring out that I'm passing it a 4 dimensional matrix when it wants a 3 dimensional one. I understand that from a programming background. What I'm struggling to understand is what i should be doing with the following call to properly construct the correct tensor:

```
    x = torch.randn(
           (batch_size, seq_length, NUM_HEADS, EMBED_DIM),
           dtype=torch.half,
            device="cuda",
     )
```

I tried leaving off the NUM_HEADS parameter and a few other techniques to modify the tensor being created, but I'm not sure what I'm missing.   Could you help please?

**Comment by MHarris021** [comment]
So I think I figured it out, I was supposed to modify the parameters to the call to torch.randr to reduce the first set of arguments to a 3 dimensional matrix. my problem was making sure that the number of heads and embedded dimensions and heads were set correctly. It seems to be working, as far as benchmarking goes. need to figure out how to make it distributed.

**Comment by fkodom** [comment]
The quick-and-dirty way to parallelize:

```python
from torch import nn
from dilated_attention_pytorch.dilated_attention import MultiheadDilatedAttention

mda = nn.DataParallel(
    MultiheadDialtedAttention(...)
)
```

^^ Not what you'd want to do for training, but it works for rough benchmarking.
